import {
  elementaryKnowledgePoints,
  elementaryQuestionPacks,
  elementaryQuestions,
} from './elementary-question-bank.js'

export const seedData = {
  users: [
    {
      id: 1,
      nickname: '小明',
      grade: '四年级',
      subject: '数学',
      memberStatus: 'active',
      memberPlan: '季会员',
      expireDate: '2026-07-12',
      totalQuestions: 156,
      accuracy: 85,
      lastActive: '2026-04-27',
      pointsBalance: 238,
      pointsTotalEarned: 420,
      pointsTotalSpent: 182,
    },
    {
      id: 2,
      nickname: '小红',
      grade: '初一',
      subject: '语文',
      memberStatus: 'expired',
      memberPlan: '月会员',
      expireDate: '2026-04-12',
      totalQuestions: 89,
      accuracy: 72,
      lastActive: '2026-04-24',
      pointsBalance: 42,
      pointsTotalEarned: 160,
      pointsTotalSpent: 118,
    },
    {
      id: 3,
      nickname: '小华',
      grade: '初三',
      subject: '物理',
      memberStatus: 'trial',
      memberPlan: null,
      expireDate: null,
      totalQuestions: 45,
      accuracy: 68,
      lastActive: '2026-04-26',
      pointsBalance: 18,
      pointsTotalEarned: 60,
      pointsTotalSpent: 42,
    },
    {
      id: 4,
      nickname: '小丽',
      grade: '五年级',
      subject: '英语',
      memberStatus: 'active',
      memberPlan: '年会员',
      expireDate: '2027-01-20',
      totalQuestions: 234,
      accuracy: 91,
      lastActive: '2026-04-27',
      pointsBalance: 516,
      pointsTotalEarned: 760,
      pointsTotalSpent: 244,
    },
    {
      id: 5,
      nickname: '小刚',
      grade: '高二',
      subject: '化学',
      memberStatus: 'none',
      memberPlan: null,
      expireDate: null,
      totalQuestions: 12,
      accuracy: 55,
      lastActive: '2026-04-20',
      pointsBalance: 8,
      pointsTotalEarned: 20,
      pointsTotalSpent: 12,
    },
  ],
  questionPacks: [
    ...elementaryQuestionPacks,
    {
      id: 'pack-1',
      name: '四年级数学每日训练',
      subject: '数学',
      grade: '四年级',
      questionCount: 10,
      difficulty: '中等',
      status: 'published',
      source: 'manual',
      isMemberOnly: false,
      accessType: 'free',
      pointCost: 0,
      createdAt: '2026-04-10',
      usageCount: 1250,
      completionRate: 85,
      estimatedTime: 18,
      roundType: 'daily',
      structure: '基础巩固4题 · 方法迁移3题 · 应用提升2题 · 易错回收1题',
    },
    {
      id: 'pack-2',
      name: '初一有理数基础训练',
      subject: '数学',
      grade: '初一',
      questionCount: 8,
      difficulty: '基础',
      status: 'published',
      source: 'manual',
      isMemberOnly: false,
      accessType: 'points',
      pointCost: 12,
      createdAt: '2026-04-08',
      usageCount: 890,
      completionRate: 72,
      estimatedTime: 16,
      roundType: 'daily',
      structure: '概念辨析2题 · 基础运算3题 · 数轴绝对值2题 · 情境应用1题',
    },
    {
      id: 'pack-3',
      name: '阅读理解强化题包',
      subject: '语文',
      grade: '五年级',
      questionCount: 8,
      difficulty: '较难',
      status: 'published',
      source: 'imported',
      isMemberOnly: true,
      accessType: 'points',
      pointCost: 28,
      createdAt: '2026-04-05',
      usageCount: 456,
      completionRate: 68,
      estimatedTime: 25,
      roundType: 'special',
      structure: '词句理解2题 · 信息提取2题 · 主旨概括2题 · 开放表达2题',
    },
    {
      id: 'pack-4',
      name: '初三物理力学专项',
      subject: '物理',
      grade: '初三',
      questionCount: 20,
      difficulty: '困难',
      status: 'draft',
      source: 'ai_generated',
      isMemberOnly: true,
      accessType: 'points',
      pointCost: 45,
      createdAt: '2026-04-12',
      usageCount: 0,
      completionRate: 0,
      estimatedTime: 35,
      roundType: 'special',
      structure: '概念判断4题 · 受力分析6题 · 计算推导6题 · 综合应用4题',
    },
    {
      id: 'pack-5',
      name: '四年级数学周测小卷',
      subject: '数学',
      grade: '四年级',
      questionCount: 5,
      difficulty: '中等',
      status: 'published',
      source: 'manual',
      isMemberOnly: false,
      accessType: 'points',
      pointCost: 18,
      createdAt: '2026-04-27',
      usageCount: 320,
      completionRate: 81,
      estimatedTime: 20,
      roundType: 'paper',
      structure: '选择2题 · 填空2题 · 应用1题 · 满分100分',
    },
  ],
  questions: [
    ...elementaryQuestions,
    {
      id: 'q1',
      packId: 'pack-1',
      content: '下列哪个数是质数？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '质数与合数',
      difficulty: '基础',
      options: ['A. 4', 'B. 6', 'C. 7', 'D. 9'],
      answer: 'C',
      explanation: '质数只能被 1 和自身整除，7 是质数。',
      trainingLevel: '基础巩固',
      source: 'manual',
    },
    {
      id: 'q2',
      packId: 'pack-1',
      content: '计算：125 × 8 = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '乘法运算',
      difficulty: '基础',
      answer: '1000',
      explanation: '125 × 8 = 1000，也可以拆成 125 × 4 × 2。',
      trainingLevel: '基础巩固',
      source: 'manual',
    },
    {
      id: 'q3',
      packId: 'pack-1',
      content: '下面哪个算式可以用“先凑整再计算”的方法更快完成？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '简便计算',
      difficulty: '基础',
      options: ['A. 25 × 4', 'B. 13 × 7', 'C. 18 + 23', 'D. 91 - 46'],
      answer: 'A',
      explanation: '25 × 4 可以直接凑成 100，是典型的凑整计算。',
      trainingLevel: '基础巩固',
      source: 'manual',
    },
    {
      id: 'q4',
      packId: 'pack-1',
      content: '36 ÷ 6 + 14 = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '四则混合运算',
      difficulty: '基础',
      answer: '20',
      explanation: '先算除法：36 ÷ 6 = 6，再算 6 + 14 = 20。',
      trainingLevel: '基础巩固',
    },
    {
      id: 'q5',
      packId: 'pack-1',
      content: '一个数既是 6 的倍数，又是 4 的倍数，下面哪个数符合？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '倍数与公倍数',
      difficulty: '中等',
      options: ['A. 8', 'B. 12', 'C. 18', 'D. 22'],
      answer: 'B',
      explanation: '12 能同时被 6 和 4 整除，所以符合条件。',
      trainingLevel: '方法迁移',
    },
    {
      id: 'q6',
      packId: 'pack-1',
      content: '把 3 个 100、4 个 10 和 6 个 1 合起来是 ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '数位与组成',
      difficulty: '基础',
      answer: '346',
      explanation: '3 个 100 是 300，4 个 10 是 40，再加 6，合起来是 346。',
      trainingLevel: '方法迁移',
    },
    {
      id: 'q7',
      packId: 'pack-1',
      content: '小明有36颗糖果，要平均分给6个小朋友，每个小朋友能分到多少颗糖果？',
      type: '应用题',
      subject: '数学',
      knowledgePoint: '除法应用',
      difficulty: '中等',
      answer: '6',
      explanation: '36 ÷ 6 = 6。',
      trainingLevel: '方法迁移',
    },
    {
      id: 'q8',
      packId: 'pack-1',
      content: '一本练习册每天做 8 页，连续做 7 天，一共做多少页？',
      type: '应用题',
      subject: '数学',
      knowledgePoint: '乘法应用',
      difficulty: '中等',
      answer: '56',
      explanation: '每天 8 页，7 天就是 8 × 7 = 56 页。',
      trainingLevel: '应用提升',
    },
    {
      id: 'q9',
      packId: 'pack-1',
      content: '一个长方形长 9 厘米、宽 4 厘米，周长是多少厘米？',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '长方形周长',
      difficulty: '中等',
      answer: '26',
      explanation: '长方形周长 = (长 + 宽) × 2 = (9 + 4) × 2 = 26。',
      trainingLevel: '应用提升',
    },
    {
      id: 'q10',
      packId: 'pack-1',
      content: '学校买来 5 箱粉笔，每箱 24 盒，已经用了 38 盒，还剩多少盒？',
      type: '应用题',
      subject: '数学',
      knowledgePoint: '两步应用题',
      difficulty: '较难',
      answer: '82',
      explanation: '先算总数 5 × 24 = 120，再算剩余 120 - 38 = 82。',
      trainingLevel: '易错回收',
    },
    {
      id: 'm1',
      packId: 'pack-2',
      content: '下列哪个数是负整数？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '有理数分类',
      difficulty: '基础',
      options: ['A. -3.5', 'B. -2', 'C. 0', 'D. 1/2'],
      answer: 'B',
      explanation: '负整数是指小于 0 的整数。-2 是小于 0 的整数。',
      trainingLevel: '概念辨析',
    },
    {
      id: 'm2',
      packId: 'pack-2',
      content: '(-5) + 3 = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '有理数加法',
      difficulty: '基础',
      answer: '-2',
      explanation: '-5 + 3 中负数绝对值更大，结果为 -2。',
      trainingLevel: '基础运算',
    },
    {
      id: 'm3',
      packId: 'pack-2',
      content: '数轴上，-4 到 0 的距离是？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '数轴与距离',
      difficulty: '基础',
      options: ['A. -4', 'B. 0', 'C. 4', 'D. 8'],
      answer: 'C',
      explanation: '距离不能为负，-4 到 0 相隔 4 个单位长度。',
      trainingLevel: '数轴绝对值',
    },
    {
      id: 'm4',
      packId: 'pack-2',
      content: '|-12| = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '绝对值',
      difficulty: '基础',
      answer: '12',
      explanation: '绝对值表示到 0 的距离，所以 |-12| = 12。',
      trainingLevel: '数轴绝对值',
    },
    {
      id: 'm5',
      packId: 'pack-2',
      content: '(-3) × 4 = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '有理数乘法',
      difficulty: '中等',
      answer: '-12',
      explanation: '负数乘正数结果为负，3 × 4 = 12，所以答案是 -12。',
      trainingLevel: '基础运算',
    },
    {
      id: 'm6',
      packId: 'pack-2',
      content: '下列比较大小正确的是？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '有理数大小比较',
      difficulty: '中等',
      options: ['A. -5 > -2', 'B. -1 < -3', 'C. 0 > -1', 'D. -4 > 2'],
      answer: 'C',
      explanation: '0 大于任何负数，所以 0 > -1 正确。',
      trainingLevel: '概念辨析',
    },
    {
      id: 'm7',
      packId: 'pack-2',
      content: '(-2)² = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '有理数乘方',
      difficulty: '中等',
      answer: '4',
      explanation: '(-2)² 表示 (-2) × (-2)，同号相乘为正，结果是 4。',
      trainingLevel: '基础运算',
    },
    {
      id: 'm8',
      packId: 'pack-2',
      content: '某地上午气温为 -3℃，下午上升 8℃，下午气温是多少？',
      type: '应用题',
      subject: '数学',
      knowledgePoint: '有理数加法应用',
      difficulty: '中等',
      answer: '5',
      explanation: '-3 + 8 = 5，所以下午气温是 5℃。',
      trainingLevel: '情境应用',
    },
    {
      id: 'p5-q1',
      packId: 'pack-5',
      content: '下列哪个算式的结果等于 360？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '乘法运算',
      difficulty: '基础',
      options: ['A. 30 × 12', 'B. 40 × 8', 'C. 60 × 5', 'D. 90 × 3'],
      answer: 'A',
      explanation: '30 × 12 = 360，其余选项分别是 320、300、270。',
      trainingLevel: '小卷选择',
      points: 20,
    },
    {
      id: 'p5-q2',
      packId: 'pack-5',
      content: '48 ÷ 6 × 5 = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '四则混合运算',
      difficulty: '基础',
      answer: '40',
      explanation: '同级运算从左到右：48 ÷ 6 = 8，8 × 5 = 40。',
      trainingLevel: '小卷填空',
      points: 20,
    },
    {
      id: 'p5-q3',
      packId: 'pack-5',
      content: '一个长方形长 12 厘米、宽 5 厘米，面积是多少平方厘米？',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '长方形面积',
      difficulty: '中等',
      answer: '60',
      explanation: '长方形面积 = 长 × 宽 = 12 × 5 = 60。',
      trainingLevel: '小卷填空',
      points: 20,
    },
    {
      id: 'p5-q4',
      packId: 'pack-5',
      content: '下面哪个数既是 3 的倍数，又是 4 的倍数？',
      type: '选择题',
      subject: '数学',
      knowledgePoint: '倍数与公倍数',
      difficulty: '中等',
      options: ['A. 9', 'B. 10', 'C. 12', 'D. 14'],
      answer: 'C',
      explanation: '12 能同时被 3 和 4 整除。',
      trainingLevel: '小卷选择',
      points: 20,
    },
    {
      id: 'p5-q5',
      packId: 'pack-5',
      content: '商店有 6 箱牛奶，每箱 24 盒，卖出 58 盒后还剩多少盒？',
      type: '应用题',
      subject: '数学',
      knowledgePoint: '两步应用题',
      difficulty: '中等',
      answer: '86',
      explanation: '先算总数 6 × 24 = 144，再算 144 - 58 = 86。',
      trainingLevel: '小卷应用',
      points: 20,
    },
  ],
  knowledgePoints: [
    ...elementaryKnowledgePoints,
    { id: 'kp-1', subject: '数学', stage: '小学', name: '乘法运算', chapter: '数与运算', gradeRange: '二年级-四年级', questionCount: 68, wrongRate: 18, status: 'active', roundAdvice: '每日口算+应用题各 1 题' },
    { id: 'kp-2', subject: '数学', stage: '小学', name: '质数与合数', chapter: '数的认识', gradeRange: '四年级-六年级', questionCount: 46, wrongRate: 26, status: 'active', roundAdvice: '概念辨析优先，搭配倍数题' },
    { id: 'kp-3', subject: '数学', stage: '小学', name: '四则混合运算', chapter: '数与运算', gradeRange: '三年级-五年级', questionCount: 72, wrongRate: 21, status: 'active', roundAdvice: '先顺序判断，再限时计算' },
    { id: 'kp-4', subject: '数学', stage: '小学', name: '两步应用题', chapter: '解决问题', gradeRange: '三年级-五年级', questionCount: 58, wrongRate: 29, status: 'active', roundAdvice: '画数量关系，减少盲算' },
    { id: 'kp-5', subject: '数学', stage: '初中', name: '有理数运算', chapter: '数与式', gradeRange: '初一-初二', questionCount: 96, wrongRate: 31, status: 'active', roundAdvice: '符号规则和绝对值交替训练' },
    { id: 'kp-6', subject: '语文', stage: '小学', name: '阅读理解', chapter: '现代文阅读', gradeRange: '三年级-六年级', questionCount: 64, wrongRate: 22, status: 'active', roundAdvice: '先信息定位，再主旨概括' },
  ],
  learningRecords: [
    { id: 'lr-1', userId: 1, user: '小明', pack: '四年级数学每日练习', subject: '数学', completedAt: '2026-04-27 09:30', total: 10, correct: 8, duration: 14 },
    { id: 'lr-2', userId: 4, user: '小丽', pack: '阅读理解强化题包', subject: '语文', completedAt: '2026-04-27 10:15', total: 8, correct: 7, duration: 21 },
    { id: 'lr-3', userId: 2, user: '小红', pack: '初一有理数基础练习', subject: '数学', completedAt: '2026-04-26 19:40', total: 15, correct: 10, duration: 23 },
  ],
  wrongQuestions: [
    { id: 'wq-1', user: '小明', subject: '数学', knowledgePoint: '质数与合数', content: '下列哪个数是质数？', wrongAnswer: 'B', correctAnswer: 'C', practiceCount: 1, mastered: false, status: 'new', statusLabel: '新错题' },
    { id: 'wq-2', user: '小红', subject: '数学', knowledgePoint: '有理数运算', content: '(-5) + 3 = ?', wrongAnswer: '2', correctAnswer: '-2', practiceCount: 2, mastered: false, status: 'reviewing', statusLabel: '复练中' },
    { id: 'wq-3', user: '小丽', subject: '语文', knowledgePoint: '阅读理解', content: '概括文章中心思想', wrongAnswer: '偏离主旨', correctAnswer: '围绕人物变化概括', practiceCount: 1, mastered: true, status: 'mastered', statusLabel: '已掌握' },
  ],
  uploadedQuestions: [
    {
      id: 'upl-1',
      user: '同学',
      content: '计算：125 × 8 = ?',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '乘法运算',
      difficulty: '基础',
      answer: '1000',
      userAnswer: '1000',
      correctionStatus: 'correct',
      source: 'uploaded',
      sourceType: 'photo',
      recognizedText: '计算：125 × 8 = ?',
      explanation: '125 × 8 = 1000，可以拆成 125 × 4 × 2。',
      uploadedAt: '2026-04-27 15:20',
      lastPracticedAt: null,
      practiceCount: 0,
    },
    {
      id: 'upl-2',
      user: '同学',
      content: '一个长方形长 9 厘米、宽 4 厘米，周长是多少厘米？',
      type: '填空题',
      subject: '数学',
      knowledgePoint: '长方形周长',
      difficulty: '中等',
      answer: '26',
      userAnswer: '24',
      correctionStatus: 'wrong',
      source: 'uploaded',
      sourceType: 'manual',
      recognizedText: '一个长方形长 9 厘米、宽 4 厘米，周长是多少厘米？',
      explanation: '长方形周长 = (长 + 宽) × 2 = 26。',
      uploadedAt: '2026-04-27 15:42',
      lastPracticedAt: null,
      practiceCount: 1,
    },
  ],
  orders: [
    { id: 'ORD001', user: '小明', plan: '季会员', planId: 'quarterly', amount: 79, status: 'paid', paymentStatus: 'paid', paymentMethod: '微信支付', provider: 'wechat_pay', transactionId: 'WX202604271030001', createdAt: '2026-04-27 10:30', paidAt: '2026-04-27 10:31', expireDate: '2026-07-26' },
    { id: 'ORD002', user: '小红', plan: '月会员', planId: 'monthly', amount: 29, status: 'paid', paymentStatus: 'paid', paymentMethod: '支付宝', provider: 'alipay', transactionId: 'ALI202604261520001', createdAt: '2026-04-26 15:20', paidAt: '2026-04-26 15:21', expireDate: '2026-05-26' },
    { id: 'ORD003', user: '小华', plan: '年会员', planId: 'yearly', amount: 199, status: 'pending', paymentStatus: 'pending', paymentMethod: '-', provider: null, transactionId: null, createdAt: '2026-04-25 09:45', paidAt: null, expireDate: '-' },
    { id: 'ORD004', user: '小丽', plan: '季会员', planId: 'quarterly', amount: 79, status: 'refunded', paymentStatus: 'refunded', paymentMethod: '微信支付', provider: 'wechat_pay', transactionId: 'WX202604241430001', createdAt: '2026-04-24 14:30', paidAt: '2026-04-24 14:31', expireDate: '-' },
  ],
  payments: [
    { id: 'PAY001', orderId: 'ORD001', provider: 'wechat_pay', channel: '微信支付', amount: 79, status: 'paid', transactionId: 'WX202604271030001', createdAt: '2026-04-27 10:30', paidAt: '2026-04-27 10:31', refundedAt: null },
    { id: 'PAY002', orderId: 'ORD002', provider: 'alipay', channel: '支付宝', amount: 29, status: 'paid', transactionId: 'ALI202604261520001', createdAt: '2026-04-26 15:20', paidAt: '2026-04-26 15:21', refundedAt: null },
    { id: 'PAY003', orderId: 'ORD003', provider: 'wechat_pay', channel: '微信支付', amount: 199, status: 'pending', transactionId: null, createdAt: '2026-04-25 09:45', paidAt: null, refundedAt: null },
    { id: 'PAY004', orderId: 'ORD004', provider: 'wechat_pay', channel: '微信支付', amount: 79, status: 'refunded', transactionId: 'WX202604241430001', createdAt: '2026-04-24 14:30', paidAt: '2026-04-24 14:31', refundedAt: '2026-04-25 08:00' },
  ],
  aiGenerationHistory: [
    { id: 'AI001', subject: '数学', grade: '四年级', knowledgePoint: '乘法运算', count: 10, status: 'published', createdAt: '2026-04-15 10:30' },
    { id: 'AI002', subject: '语文', grade: '五年级', knowledgePoint: '阅读理解', count: 8, status: 'review', createdAt: '2026-04-14 15:20' },
    { id: 'AI003', subject: '英语', grade: '初一', knowledgePoint: '语法', count: 15, status: 'draft', createdAt: '2026-04-13 09:45' },
  ],
  membershipPlans: [
    { id: 'monthly', name: '月会员', price: 29, originalPrice: 39, duration: 30, activeUsers: 450, renewalRate: 45, status: 'active' },
    { id: 'quarterly', name: '季会员', price: 79, originalPrice: 117, duration: 90, activeUsers: 680, renewalRate: 68, status: 'active' },
    { id: 'yearly', name: '年会员', price: 199, originalPrice: 468, duration: 365, activeUsers: 150, renewalRate: 82, status: 'active' },
  ],
  pointPackages: [
    { id: 'points-100', name: '体验积分包', points: 100, bonusPoints: 0, price: 9.9, originalPrice: 12, recommended: false, status: 'active', description: '适合先解锁少量专项题包' },
    { id: 'points-360', name: '常用积分包', points: 300, bonusPoints: 60, price: 29.9, originalPrice: 39, recommended: true, status: 'active', description: '适合持续解锁教材同步和专项题包' },
    { id: 'points-1000', name: '高频积分包', points: 880, bonusPoints: 120, price: 69.9, originalPrice: 99, recommended: false, status: 'active', description: '适合多学科、多年级题包解锁' },
  ],
  pointRules: [
    { action: 'content_purchase', name: '解锁题包', variableCost: true, unit: '题包', enabled: true },
    { action: 'practice_reward', name: '完成练习奖励', reward: 5, unit: '组', enabled: true },
    { action: 'checkin', name: '每日登录奖励', reward: 5, unit: '天', enabled: true },
  ],
  pointTransactions: [
    { id: 'PT001', user: '小明', type: 'credit', action: 'purchase', points: 360, balanceAfter: 238, note: '购买常用积分包', relatedId: 'ORD-P001', createdAt: '2026-04-27 10:32', operator: 'system' },
    { id: 'PT002', user: '小明', type: 'debit', action: 'content_purchase', points: 28, balanceAfter: 210, note: '购买题包：阅读理解强化题包', relatedId: 'CP001', createdAt: '2026-04-27 12:10', operator: 'system' },
    { id: 'PT003', user: '小丽', type: 'credit', action: 'practice_reward', points: 5, balanceAfter: 516, note: '完成阅读理解强化题包', relatedId: 'lr-2', createdAt: '2026-04-27 10:16', operator: 'system' },
  ],
  contentPurchases: [
    { id: 'CP001', user: '小明', packId: 'pack-3', pointCost: 28, title: '阅读理解强化题包', purchasedAt: '2026-04-27 12:10', pointTransactionId: 'PT002' },
  ],
  settings: {
    appName: '题小助',
    adminUsername: 'admin',
    uploadLimitPerDay: 20,
    trialDays: 7,
    aiProvider: 'mock-compatible',
    contentReviewRequired: true,
    maintenanceMode: false,
    monetizationMode: 'points',
    pointsFeatureVisible: true,
    paymentFeatureVisible: false,
    paymentMode: 'test',
    paymentProviders: ['wechat_pay', 'alipay'],
  },
}

const curriculumPackIds = new Set(elementaryQuestionPacks.map(pack => pack.id))

seedData.questionPacks = seedData.questionPacks.filter(pack => curriculumPackIds.has(pack.id))
seedData.questions = seedData.questions.filter(question => curriculumPackIds.has(question.packId))
seedData.knowledgePoints = seedData.knowledgePoints.filter(point => String(point.id).startsWith('kp-primary'))

const pickPack = ({ subject, grade, series, semester }) => {
  const pack = seedData.questionPacks.find((item) => (
    item.subject === subject
    && item.grade === grade
    && item.series === series
    && (semester ? item.semester === semester : true)
  ))
  if (!pack) {
    throw new Error(`Missing curriculum pack: ${subject}-${grade}-${series}${semester ? `-${semester}` : ''}`)
  }
  return pack
}

const questionsForPack = (packId) => seedData.questions.filter(question => question.packId === packId)

const pickQuestionSample = (pack, index = 0) => {
  const question = questionsForPack(pack.id)[index]
  if (!question) {
    throw new Error(`Missing sample question for pack ${pack.id}`)
  }
  return question
}

const mathTextbookPack = pickPack({ subject: '数学', grade: '四年级', series: 'textbook', semester: '上册' })
const mathSpecialPack = pickPack({ subject: '数学', grade: '四年级', series: 'special' })
const chineseTextbookPack = pickPack({ subject: '语文', grade: '五年级', series: 'textbook', semester: '上册' })
const chineseSpecialPack = pickPack({ subject: '语文', grade: '五年级', series: 'special' })
const englishTextbookPack = pickPack({ subject: '英语', grade: '三年级', series: 'textbook', semester: '上册' })
const englishPaperPack = pickPack({ subject: '英语', grade: '三年级', series: 'paper', semester: '上册' })
const gradeSixMathPaperPack = pickPack({ subject: '数学', grade: '六年级', series: 'paper', semester: '上册' })

const mathTextbookQuestion = pickQuestionSample(mathTextbookPack, 0)
const mathSpecialQuestion = pickQuestionSample(mathSpecialPack, 1)
const chineseSpecialQuestion = pickQuestionSample(chineseSpecialPack, 0)
const englishPaperQuestion = pickQuestionSample(englishPaperPack, 2)

seedData.users = [
  {
    id: 1,
    nickname: '小明',
    grade: '四年级',
    subject: '数学',
    memberStatus: 'active',
    memberPlan: '季会员',
    expireDate: '2026-07-12',
    totalQuestions: 156,
    accuracy: 85,
    lastActive: '2026-05-02',
    pointsBalance: 238,
    pointsTotalEarned: 420,
    pointsTotalSpent: 182,
  },
  {
    id: 2,
    nickname: '小雅',
    grade: '三年级',
    subject: '英语',
    memberStatus: 'trial',
    memberPlan: null,
    expireDate: null,
    totalQuestions: 94,
    accuracy: 76,
    lastActive: '2026-05-01',
    pointsBalance: 66,
    pointsTotalEarned: 120,
    pointsTotalSpent: 54,
  },
  {
    id: 3,
    nickname: '小丽',
    grade: '五年级',
    subject: '语文',
    memberStatus: 'active',
    memberPlan: '年会员',
    expireDate: '2027-01-20',
    totalQuestions: 234,
    accuracy: 91,
    lastActive: '2026-05-02',
    pointsBalance: 516,
    pointsTotalEarned: 760,
    pointsTotalSpent: 244,
  },
  {
    id: 4,
    nickname: '小航',
    grade: '六年级',
    subject: '数学',
    memberStatus: 'none',
    memberPlan: null,
    expireDate: null,
    totalQuestions: 63,
    accuracy: 69,
    lastActive: '2026-04-30',
    pointsBalance: 18,
    pointsTotalEarned: 58,
    pointsTotalSpent: 40,
  },
  {
    id: 5,
    nickname: '小宁',
    grade: '四年级',
    subject: '语文',
    memberStatus: 'active',
    memberPlan: '月会员',
    expireDate: '2026-05-28',
    totalQuestions: 122,
    accuracy: 82,
    lastActive: '2026-05-01',
    pointsBalance: 128,
    pointsTotalEarned: 220,
    pointsTotalSpent: 92,
  },
]

seedData.learningRecords = [
  {
    id: 'lr-1',
    userId: 1,
    user: '小明',
    packId: mathTextbookPack.id,
    pack: mathTextbookPack.name,
    subject: '数学',
    completedAt: '2026-05-02 09:30',
    total: mathTextbookPack.questionCount,
    correct: 19,
    duration: 21,
    weakKnowledgePoints: [mathTextbookQuestion.knowledgePoint, mathSpecialQuestion.knowledgePoint],
  },
  {
    id: 'lr-2',
    userId: 3,
    user: '小丽',
    packId: chineseSpecialPack.id,
    pack: chineseSpecialPack.name,
    subject: '语文',
    completedAt: '2026-05-02 10:15',
    total: chineseSpecialPack.questionCount,
    correct: 24,
    duration: 27,
    weakKnowledgePoints: [chineseSpecialQuestion.knowledgePoint],
  },
  {
    id: 'lr-3',
    userId: 2,
    user: '小雅',
    packId: englishTextbookPack.id,
    pack: englishTextbookPack.name,
    subject: '英语',
    completedAt: '2026-05-01 19:40',
    total: englishTextbookPack.questionCount,
    correct: 18,
    duration: 20,
    weakKnowledgePoints: [englishPaperQuestion.knowledgePoint],
  },
  {
    id: 'lr-4',
    userId: 4,
    user: '小航',
    packId: gradeSixMathPaperPack.id,
    pack: gradeSixMathPaperPack.name,
    subject: '数学',
    completedAt: '2026-04-30 18:20',
    total: gradeSixMathPaperPack.questionCount,
    correct: 22,
    duration: 31,
    weakKnowledgePoints: [pickQuestionSample(gradeSixMathPaperPack, 0).knowledgePoint],
  },
]

seedData.wrongQuestions = [
  {
    id: 'wq-1',
    user: '小明',
    subject: '数学',
    knowledgePoint: mathTextbookQuestion.knowledgePoint,
    content: mathTextbookQuestion.content,
    wrongAnswer: 'B',
    correctAnswer: mathTextbookQuestion.answer,
    practiceCount: 1,
    mastered: false,
    status: 'new',
    statusLabel: '新错题',
  },
  {
    id: 'wq-2',
    user: '小雅',
    subject: '英语',
    knowledgePoint: englishPaperQuestion.knowledgePoint,
    content: englishPaperQuestion.content,
    wrongAnswer: 'A',
    correctAnswer: englishPaperQuestion.answer,
    practiceCount: 2,
    mastered: false,
    status: 'reviewing',
    statusLabel: '复练中',
  },
  {
    id: 'wq-3',
    user: '小丽',
    subject: '语文',
    knowledgePoint: chineseSpecialQuestion.knowledgePoint,
    content: chineseSpecialQuestion.content,
    wrongAnswer: '偏离主旨',
    correctAnswer: chineseSpecialQuestion.answer,
    practiceCount: 1,
    mastered: true,
    status: 'mastered',
    statusLabel: '已掌握',
  },
]

seedData.aiGenerationHistory = [
  { id: 'AI001', subject: '数学', grade: '四年级', knowledgePoint: mathSpecialQuestion.knowledgePoint, count: 12, status: 'published', createdAt: '2026-05-01 10:30' },
  { id: 'AI002', subject: '语文', grade: '五年级', knowledgePoint: chineseSpecialQuestion.knowledgePoint, count: 10, status: 'review', createdAt: '2026-04-30 15:20' },
  { id: 'AI003', subject: '英语', grade: '三年级', knowledgePoint: englishPaperQuestion.knowledgePoint, count: 14, status: 'draft', createdAt: '2026-04-29 09:45' },
]

seedData.orders = [
  { id: 'ORD001', user: '小明', plan: '季会员', planId: 'quarterly', amount: 79, status: 'paid', paymentStatus: 'paid', paymentMethod: '微信支付', provider: 'wechat_pay', transactionId: 'WX202605021030001', createdAt: '2026-05-02 10:30', paidAt: '2026-05-02 10:31', expireDate: '2026-07-31' },
  { id: 'ORD002', user: '小宁', plan: '月会员', planId: 'monthly', amount: 29, status: 'paid', paymentStatus: 'paid', paymentMethod: '支付宝', provider: 'alipay', transactionId: 'ALI202605011520001', createdAt: '2026-05-01 15:20', paidAt: '2026-05-01 15:21', expireDate: '2026-05-31' },
  { id: 'ORD003', user: '小雅', plan: '年会员', planId: 'yearly', amount: 199, status: 'pending', paymentStatus: 'pending', paymentMethod: '-', provider: null, transactionId: null, createdAt: '2026-04-30 09:45', paidAt: null, expireDate: '-' },
  { id: 'ORD004', user: '小丽', plan: '季会员', planId: 'quarterly', amount: 79, status: 'refunded', paymentStatus: 'refunded', paymentMethod: '微信支付', provider: 'wechat_pay', transactionId: 'WX202604291430001', createdAt: '2026-04-29 14:30', paidAt: '2026-04-29 14:31', expireDate: '-' },
]

seedData.payments = [
  { id: 'PAY001', orderId: 'ORD001', provider: 'wechat_pay', channel: '微信支付', amount: 79, status: 'paid', transactionId: 'WX202605021030001', createdAt: '2026-05-02 10:30', paidAt: '2026-05-02 10:31', refundedAt: null },
  { id: 'PAY002', orderId: 'ORD002', provider: 'alipay', channel: '支付宝', amount: 29, status: 'paid', transactionId: 'ALI202605011520001', createdAt: '2026-05-01 15:20', paidAt: '2026-05-01 15:21', refundedAt: null },
  { id: 'PAY003', orderId: 'ORD003', provider: 'wechat_pay', channel: '微信支付', amount: 199, status: 'pending', transactionId: null, createdAt: '2026-04-30 09:45', paidAt: null, refundedAt: null },
  { id: 'PAY004', orderId: 'ORD004', provider: 'wechat_pay', channel: '微信支付', amount: 79, status: 'refunded', transactionId: 'WX202604291430001', createdAt: '2026-04-29 14:30', paidAt: '2026-04-29 14:31', refundedAt: '2026-04-30 08:00' },
]

seedData.pointTransactions = [
  { id: 'PT001', user: '小明', type: 'credit', action: 'purchase', points: 360, balanceAfter: 238, note: '购买常用积分包', relatedId: 'ORD-P001', createdAt: '2026-05-02 10:32', operator: 'system' },
  { id: 'PT002', user: '小明', type: 'debit', action: 'content_purchase', points: Number(mathSpecialPack.pointCost || 0), balanceAfter: 216, note: `购买题包：${mathSpecialPack.name}`, relatedId: 'CP001', createdAt: '2026-05-02 12:10', operator: 'system' },
  { id: 'PT003', user: '小丽', type: 'credit', action: 'practice_reward', points: 5, balanceAfter: 516, note: `完成${chineseSpecialPack.name}`, relatedId: 'lr-2', createdAt: '2026-05-02 10:16', operator: 'system' },
]

seedData.contentPurchases = [
  { id: 'CP001', user: '小明', packId: mathSpecialPack.id, pointCost: Number(mathSpecialPack.pointCost || 0), title: mathSpecialPack.name, purchasedAt: '2026-05-02 12:10', pointTransactionId: 'PT002' },
  { id: 'CP002', user: '小雅', packId: englishPaperPack.id, pointCost: Number(englishPaperPack.pointCost || 0), title: englishPaperPack.name, purchasedAt: '2026-05-01 20:10', pointTransactionId: null },
]
